volumes:   
  nodemodules:

services:
  spa:
    image: websec-spa
    build:
      context: ./SPA
      dockerfile: Dockerfile
    volumes:
      - ./SPA:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    networks:
     - default 
    ports:
     - 3000:3000

  api:
    image: websec-api
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5172
    volumes:
      - ./API:/app
    networks:
     - default 
    ports:
     - 5172:5172
    
  opaserver:
    image: openpolicyagent/opa:latest
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    environment:
      - OPA_LOG_TIMESTAMP_FORMAT="2006-01-02T15:04:05.999999999Z07:00"
    command:
      - "run"
      - "-l"
      - "debug"
      - "--server"
      - "/opa.rego"
    #  - "--config-file"
    #  - "/config.yaml"
      - "--log-format"
      - "json-pretty"
      - "--watch"
    volumes:
    - ./OPA/opa.rego:/opa.rego
   # - ./OPA/config.yaml:/config.yaml
    networks:
     - default  
    ports:
     - 8181:8181 